#!/usr/bin/env python
# -*- coding: ANSI_X3.4-1968 -*-
#
# generated by wxGlade 0.6.8 on Wed Apr 22 11:06:24 2015
#

import wx
import socket, sys
from struct import *
from scapy.all import *
from StringIO import StringIO


# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.button_1 = wx.Button(self, wx.ID_ANY, _("Start"))
        self.listbox = wx.ListBox(self, wx.ID_ANY, choices=[])

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.startButton, self.button_1)
        self.Bind(wx.EVT_LISTBOX, self.listBoxHandler, self.listbox)
        # end wxGlade
        
    
    def startAnalyzer(self):
        self.listbox.Append("Welcome to the Network Protocol Analyzer")
        string = sniff(prn=lambda x: x.summary(),count=30)
        capture = StringIO()
        save_stdout = sys.stdout
        sys.stdout = capture
        string.show()
        sys.stdout = save_stdout
        self.listbox.Append(capture.getvalue())
        self.listbox.Append(' ')
            
            

    def __set_properties(self):
        # begin wxGlade: MyFrame.__set_properties
        self.SetTitle(_("frame_1"))
        self.button_1.SetMinSize((90, 42))
        self.listbox.SetMinSize((534, 340))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MyFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.button_1, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_1.Add(self.listbox, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def startButton(self, event):
        print "Calling startAnalyzer"
        self.startAnalyzer()

    def listBoxHandler(self, event):  # wxGlade: MyFrame.<event_handler>
        print "Event handler 'listBoxHandler' not implemented!"
        event.Skip()

# end of class MyFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MyFrame(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
